// Substitui pelos teus projectos reais (imagens, links, descrições)
const projectsData = [
    {
        title: 'Sistema de Gestão Escolar',
        description: 'Plataforma web para gestão de notas e matrículas, com painel administrativo.',
        stack: ['Java', 'Spring Boot', 'MySQL', 'TailwindCSS', 'React.js'],
        status: 'private', // public | progress | private
        link: '#',
        img: "assets/projects/project05.png",
        featured: true,
    },
    {
        title: 'Cartaz',
        description: 'Cartaz de referencia para o dia Internacional da Mulher.',
        stack: ['Canva'],
        status: 'private',
        link: '#',
        img: "assets/projects/project04.png",
        featured: true,
    },
    {
        title: 'Hamburguer 3D',
        description: 'Modelagem de um hamburguer 3D, com recurso a imagem, blender, animacao, ect.',
        stack: ['Blender', 'Animate 3D'],
        status: 'private',
        link: '#',
        img: "assets/projects/project03.png",
        featured: true,
    },
    {
        title: 'Website',
        description: 'Website feito para uma empresa de tecnologia.',
        stack: ['Blender', 'Pencil2D'],
        status: 'private',
        link: '#',
        img: "assets/projects/project01.png",
        featured: false,
    },
    {
        title: 'Dado 3D',
        description: 'Modelagem de um objecto 3D, com animacoes.',
        stack: ['Blender', 'Animated 3D'],
        status: 'private',
        link: '#',
        img: "assets/projects/project02.png",
        featured: false,
    },
    {
        title: 'SGTE',
        description: 'Sistema de gestao de transporte escolar.',
        stack: ['HTML', 'CSS', 'JS', 'PHP', 'BootStrap', 'MySQL'],
        status: 'private',
        link: 'https://transporteescolar.ifree.page',
        img: "assets/projects/project06.png",
        featured: false,
    },
];
